title:             Stefan Glorch
email:             info@sglorch.de
description:
author:            Stefan Glorch
baseurl:           ""
url:               "https://sglorch.de"

# Social Profiles
twitter_username:
github_username:   sglorch
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  #https://github.com/bdesham/reading_time
  - jekyll-gist #https://github.com/jekyll/jekyll-gist
  - jekyll-seo-tag #https://github.com/jekyll/jekyll-seo-tag
  #- jekyll-github-metadata
  - jekyll-target-blank
  - jekyll-sitemap
sass:
  style: compressed
