title:             Stefan Glorch
email:             stefan.glorch@gym-hennef.de
description:       
author:            Start Bootstrap
baseurl:           ""
url:               "https://sglorch.me"

# Social Profiles
twitter_username:  
github_username:   sglorch
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  #https://github.com/bdesham/reading_time
  - jekyll-gist #https://github.com/jekyll/jekyll-gist
  #https://github.com/jekyll/jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-target-blank
  - jekyll-sitemap